server:
  port: 8088
  servlet:
    context-path: /uprofile
  tomcat:
    uri-encoding: utf-8
spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
    
spring.datasource:
    name: resume
    url: jdbc:h2:~/uprofile/uprofiledb
    username: uprofile
    password: uprofile
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver

          
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.good.ocr.model  # 注意：对应实体类的路径
